# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 04:31
from __future__ import unicode_literals

import accounts.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=accounts.models.PhoneNumberField(max_length=20, validators=[django.core.validators.RegexValidator('^01[016789][1-9]\\d{6,7}$', message='휴대폰 번호를 입력해주세요.'), accounts.models.ktf_validator, django.core.validators.RegexValidator('^01[016789][1-9]\\d{6,7}$', message='휴대폰 번호를 입력해주세요.'), accounts.models.ktf_validator, django.core.validators.RegexValidator('^01[016789][1-9]\\d{6,7}$', message='휴대폰 번호를 입력해주세요.'), accounts.models.ktf_validator]),
        ),
    ]
