# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.CharField(max_length=300),
        ),
    ]
