# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 09:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_1_1', models.CharField(blank=True, max_length=20, null=True)),
                ('style_1_2', models.CharField(blank=True, max_length=20, null=True)),
                ('style_1_3', models.CharField(blank=True, max_length=20, null=True)),
                ('style_2', models.CharField(blank=True, max_length=20, null=True)),
                ('style_3', models.CharField(blank=True, max_length=40, null=True)),
                ('style_4', models.CharField(blank=True, max_length=10, null=True)),
                ('style_5', models.CharField(blank=True, max_length=100, null=True)),
                ('style_6', models.CharField(blank=True, max_length=60, null=True)),
                ('style_7', models.CharField(blank=True, max_length=20, null=True)),
                ('style_8', models.CharField(blank=True, max_length=40, null=True)),
                ('style_9', models.CharField(blank=True, max_length=10, null=True)),
                ('style_10', models.CharField(blank=True, max_length=100, null=True)),
                ('style_11', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('curriculum', models.CharField(max_length=20)),
                ('size_top', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=6)),
                ('size_bottom', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=6)),
                ('kakao', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 6, 23, 9, 2, 21, 388902))),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2016, 7, 23, 9, 2, 21, 388930))),
                ('name', models.CharField(max_length=40, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
