# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='start',
            name='address',
            field=models.TextField(default=datetime.datetime(2016, 6, 6, 16, 18, 59, 600183, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
