# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 16, 10, 30, 26, 284953)),
        ),
        migrations.AlterField(
            model_name='start',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 10, 30, 26, 284986)),
        ),
    ]
