# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 09:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 23, 9, 2, 31, 953487)),
        ),
        migrations.AlterField(
            model_name='start',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 23, 9, 2, 31, 953519)),
        ),
    ]
