# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_start_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='start',
            name='style',
            field=models.CharField(choices=[('Street', 'street'), ('Casual', 'casual'), ('Both', 'both')], default='street', max_length=6),
        ),
    ]
