# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_start_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='style',
            field=models.CharField(choices=[('street', 'Street'), ('casual', 'Casual'), ('both', 'Both')], default='street', max_length=6),
        ),
    ]
